owner: ZeroHost-Code
repo: status

sites:
  - name: Home Page
    url: https://zero-host.org
  - name: Dashboard
    url: https://dashboard.zero-host.org
  - name: Pyrodactyl
    url: https://panel.zero-host.org
  - name: Links Hub
    url: https://hub.zero-host.org
  - name: Node Next
    url: "https://node2.zero-host.org:8080"
  - name: Node Nebula
    url: "https://node1.zero-host.org:8080"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.zero-host.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ZeroHost
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
