owner: ZeroHost-Code
repo: status

sites:
  - name: Home Page
    url: https://zero-host.org
  - name: Dashboard
    url: https://dashboard.zero-host.org
  - name: Pyrodactyl
    url: https://panel.zero-host.org
  - name: Links Hub
    url: https://hub.zero-host.org
  - name: Node Next
    url: "https://node2.zero-host.org:8080"
    expectedStatusCodes:
      - 200
      - 401
  - name: Node Nebula
    url: "https://node1.zero-host.org:8080"
    expectedStatusCodes:
      - 200
      - 401

status-website:
  cname: status.zero-host.org
  favicon: https://img.zero-host.org/assets/picto.png
  logoUrl: https://img.zero-host.org/assets/picto.svg
  faviconSvg: https://img.zero-host.org/assets/picto.svg
  name: ZeroHost
  introTitle: "**ZeroHost** status"
  introMessage: View the status of your ZeroHost services in real time, switching between the web and the nodes
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/
    - title: Dashboard
      href: https://dash.zero-host.org
